name: check

on: [push]

jobs:
  ## ------------------------------------------------
  ## install cplay without any modules
  ## ------------------------------------------------
  install:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
      - uses: actions/checkout@v2
      - name: install-clay
        uses: ./
        with:
          ci: false
      - name: which cplay
        run: which cplay
      - name: cplay --version
        run: cplay --version

  ## ------------------------------------------------
  ## install a module using cplay
  ## ------------------------------------------------
  install_one:
    runs-on: ubuntu-latest
    name: "Install a single module"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay A1z-Html
        uses: ./
        with:
          install: "A1z-Html"
          ci: false

  ## ------------------------------------------------
  ## Install without tests and args
  ## ------------------------------------------------
  install_notests:
    runs-on: ubuntu-latest
    name: "Install without tests and args"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay A1z-Html
        uses: ./
        with:
          install: "A1z-Html"
          tests: false
          args: "--reinstall --installdir vendor"
          ci: false

  ## ------------------------------------------------
  ## Install two modules
  ## ------------------------------------------------
  install_two:
    runs-on: ubuntu-latest
    name: "Install two modules"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay abbreviation A1z-Html
        uses: ./
        with:
          install: |
            abbreviation
            ACH
          ci: false

  ## ------------------------------------------------
  ## Install using a cpanfile
  ## ------------------------------------------------
  install_cpanfile:
    runs-on: ubuntu-latest
    name: "Install using a cpanfile"
    steps:
      # for now install missing dependencies using cpm
      ### FIXME remove once all deps are indexed
      - uses: perl-actions/install-cpm@v1.1
        with:
          install: "Module::CPANfile"
      # ......
      - uses: actions/checkout@v2
      - name: "Create a cpanfile"
        run: |
          echo "requires 'A1z-Html';" >> cpanfile
      - name: install-with-cplay cpanfile
        uses: ./
        with:
          cpanfile: "cpanfile"
          ci: false

  ## ------------------------------------------------
  ## Install from a tarball
  ## ------------------------------------------------
  install_from_tarball:
    runs-on: ubuntu-latest
    name: "Install from tarball"
    steps:
      - uses: actions/checkout@v2
      - name: "install-with-cplay --from-tarball"
        uses: ./
        with:
          tarball: "https://github.com/pause-play/A1z-Html/archive/p5.tar.gz"
          ci: false

  ## ------------------------------------------------
  ## testing with Perl from perl-tester
  ## ------------------------------------------------
  perl:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.30"
          - "5.28"
          # ...

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:

      - name: perl -V
        run: perl -V

      - uses: actions/checkout@v2
      - name: "install-with-cplay"

        uses: ./
        with:
          sudo: false
          install: |
            abbreviation
            ACH
      - run: perl -Mabbreviation -e1
      - run: perl -ACH -e1

